### ISSUE TITLE
Cargo icons edit cargo market y freigt market 

### ISSUE THREAD

**Issue by PUNCHAPLAY** [WerewolfCustoms/ModsStudio2IssueBoard#261]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by PUNCHAPLAY** [comment]
the idea project is to make a cargo market to edit your own cargoes in ets2 and ats, it is the same as in the cargo perp container only that it is cargo with its own icon...
that it has its own material, which is what contains its own icon, and also that it be edited by freigt market, like editing trailer standalope but with its own edited load..


It would be two projects, one part the cargo market only editing the cargo with its material and the other editing the cargo with its standalope trailer, the one that would be for the company, and incidentally editing the trailers that belong to the company ... no from the now trailer...

**Comment by PUNCHAPLAY** [comment]
thanks for the work I hope you do those projects for me... thanks to this technology it improves my creativity...

**Comment by WerewolfCustoms** [comment]
We are working on the cargo improvements for the next release.
We might not cover absolutely all that you mention, but most of these things will be added or fixed.

https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/issues?q=is%3Aissue+is%3Aopen+cargo
This is the complete list of the cargo issues we're working on, and as you can see, a lot of them are already done. (Ready for review). 👍 

I'll close this issue for now, since it mostly duplicates our other issues.
Feel free to re-open it after the release if we missed anything.
