### ISSUE TITLE
Update AI Traffic Templates so that Spawn Ratios are controlled by Countries or US State

### ISSUE THREAD

**Issue by brayerip** [WerewolfCustoms/ModsStudio2IssueBoard#282]
An addition to the XML for AI traffic trailers and trucks to only be available for certain trucks and trailers

Link to a pastebin of my XML I edited from the MS2 templates folder:
https://pastebin.com/hrYGDrGk

**Comment by pete-agreatguy** [comment]
Would need to ...

- [ ] Create a new array variable to store countries (ETS2) / US States (ATS)

- Seems that ATS stores the US states as "country" also:
- ETS2 = ...extracted_146\def\country\[country].sui
- ATS = ...extracted\def\country\[us_state].sui

- [ ] Give users the choice of either (1) set spawn ratio for all countries / states ... or ... (2) specify each country / state spawn ratio

- Use of an IF STATEMENT or is there a better way of doing this?
- In GUI use a checkbox for the different options?

- [ ] GUI changes

**Comment by pete-agreatguy** [comment]
**How to control how AI Traffic spawn in specific countries**

If you want to see your AI traffic everywhere in game, then there is no need to do this  

https://modding.scssoft.com/wiki/Games/ETS2/Modding_guides/1.4.1#Changes_in_AI_definition
 https://modding.scssoft.com/wiki/Games/ETS2/Modding_guides/1.25#Traffic

https://modding.scssoft.com/wiki/Games/ETS2/Modding_guides/1.43#Traffic

Example for UK ...

Create the following sii file ...def\country\uk\traffic.laurai.sii with the following code (x2 vehicles in this example but you can add as many as you like):

```
SiiNunit
{
     country_traffic_info : .country.info.traffic.ms2_laurai1_look1 {
     object: traffic.ms2_laurai1_look1
     spawn_frequency : 4
}
{
     country_traffic_info : .country.info.traffic.ms2_laurai2_look1 {
     object: traffic.ms2_laurai2_look1
     spawn_frequency : 4
}
}
}
```

For the above the "country_traffic_info: .country.info.traffic.[traffic_vehicle]" and "object: traffic.[traffic_vehicle] link to the vehicle sui found in ... def\vehicle\ai, in the example above it would be ms2_laurai1_look1.sui and ms2_laurai2_look1.sui.

IMPORTANT NOTE: If the frequency is zero, the vehicle is not generated in that country. If file for specified combination of country and vehicle does not exist, a default frequency of 1 will be used.

**How to make vehicle spawn only in UK**

You would need to copy the above ...def\country\uk\traffic.laurai.sii file into each country folder and set the spawn ratio to 0 so that the vehicle only spawns in the UK.

**How to control spawn ratios for different countries**

You would need to copy the above ...def\country\uk\traffic.laurai.sii file into each country folder and set different spawn ratios for the vehicles within, keeping the spawn values different to another country. Remember, we recommend a spawn ratio of between 1.0 and 4.0; no higher. The higher the spawn value, the more frequent a vehicle will appear in ai traffic in game.

![image](https://user-images.githubusercontent.com/74508456/216815856-740dceb1-ab21-4aaf-9779-2d405f174020.png)
