### ISSUE TITLE
B-Double in traffic

### ISSUE THREAD

**Issue by fosloks1** [WerewolfCustoms/ModsStudio2IssueBoard#315]
B-Double trailers will be an interesting addition to the traffic.

**Comment by WerewolfCustoms** [comment]
I agree. 👍 

Have to see if SCS has any already in traffic... honestly, I can't remember if I saw any. 🤔

**Comment by fosloks1** [comment]
yes, scs have b-double in traffic, i`ll attach an file here.
[trailer.zip](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/files/10803842/trailer.zip)

**Comment by Mike7O** [comment]
I did a few custom project with these trailerconfigurations ...but it would be better if it was enabled inside the existing ones to add additional trailerconfigs..instead of multiple projectfolders

![Skärmbild 2023-03-12 192004](https://user-images.githubusercontent.com/66170614/224564430-195678e2-844b-438f-b742-144bd44b28e3.png)

however, these AItrafficdoubles seems to have issues which SCS haven't solved yet, they get broken if hit by any other vehicles ...blocking roads... 😄
