### ISSUE TITLE
Renaming of rear low boy mudflaps for ATS

### ISSUE THREAD

**Issue by Paulycustomskins** [WerewolfCustoms/ModsStudio2IssueBoard#352]
![Screenshot_53](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/assets/72619819/7fc2b96d-a63d-46c7-b190-bea7a4dc54da)
could we rename this to make it easier for members 
Low Boy - Jeep (articulated front dolly)

**Comment by Gogglees56** [comment]
Yes it does Pete. I guess the problem is one of terminology and what we here in North America call the components that make up a triple lowboy. What is called a Jeep in MS 2 is what we call a Stinger here in my part of the World. A Goose Neck is whole other kind of trailer. That is what we call a Jeep out here. 

I got lost in the terminology. Thanks for getting back to me. I appreciate everything you guys do for the community. Thanks!
