### ISSUE TITLE
Improved activation wizard

### ISSUE THREAD

**Issue by pete-agreatguy** [WerewolfCustoms/ModsStudio2IssueBoard#381]
**Describe the bug**
I'm unsure if this is a bug or not, or if it is intended to be implemented like this but back up email suggests to use a different email than originally entered.

**To Reproduce**
Download activation wizard v2022.03 and activate pro using the backup email send a code way but using the same email address as originally used :)

**Expected behaviour**
Not sure?

**Screenshots**
![image](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/assets/74508456/e7dbdce4-b1f8-498a-99c5-40b9f11fb24a)

**Desktop (please complete the following information):**
Activation Wizard Programme v2022.03 (separate from MS2 main app)

**Additional context**
Nope.

**Comment by WerewolfCustoms** [comment]
@pete-agreatguy After checking this - I am sure that it's like this by design. Backup email means (for us) that we send an email using a backup server (Gmail) instead of our original via SendGrid.

I did however go over the activation wizard and fix some issues:
- improved logging
- added option to delete a license
