### ISSUE TITLE
AI Traffic Truck - Duplicate Option links the image to original one and changes together

### ISSUE THREAD

**Issue by Mike7O** [WerewolfCustoms/ModsStudio2IssueBoard#403]
**Describe the bug**
**AI Traffic Truck** - Duplicate Option links the image to original one and changes together 
well spotted by @MarianGMC
https://discord.com/channels/611134812471820348/1021379459703652362/1167981566912385084

**To Reproduce**
1. Create AI Traffic Truck template add content to it
2. Duplicate the **Traffic Truck**
3. Change the content of it, replace Image with a new one
4. Checking the original **Traffic Truck** it has changed the image to the one added in the Duplicated template.

**Expected behavior**
To keep it's original image and also the new image in each template

**Screenshots**
videoclip added in DEV,
https://discord.com/channels/611134812471820348/611170373773295616/1167986467361005710

**Desktop (please complete the following information):**
 - Version 2023.2

**Additional context**
Same behavior in both ETS2 and ATS !

**Comment by WerewolfCustoms** [comment]
Like I said in Discord - this is my proposed solution...
Seems to work. I am rushing a bit since I would like to build a release candidate today.
@AdamLabrosse  - If there's something else you were thinking of, feel free to do it and to reopen the issue :) 👍 

![image](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/assets/8348467/f7d13043-2c79-4dcd-a13e-0c6a51d8adbd)

**Comment by AdamLabrosse** [comment]
No, I found exactly the same solution.
