### ISSUE TITLE
Adding more than 1 Windscreen decals

### ISSUE THREAD

**Issue by Paulycustomskins** [WerewolfCustoms/ModsStudio2IssueBoard#511]
Ive been doing a couple of windscreen decals lately and ive been asked if they could have 2 decals on at same time,as you know we cant unless i make it with both on,so could it be done that we can add more than 1 windscreen decal on at a time maybe 2 or 3.

**Comment by AdamLabrosse** [comment]
I suppose you would like a feature like defining two different windscreen decals in your project (for the same truck) and applying one, the other or both on one or more trucks, each having different combination.

1. SCS truck model has only one hook-up to apply an accessory on windscreen so only one model can be selected and apply on this hook-up.
2. We can define different layer in one model, letting user define a skin for each layer in MS2 interface. Doing so user should define a template for each combination. That can become a nightmare to do with 3 layers. And this solution should not be very different from using the actual template and adding layers to a skin using drawing software.
3. A smart solution should be to introduce 3 models, one for each layer of the windscreen (multiply by two for the interior models). The first model would add an extra hook-up for selecting a second layer model. And second model doing the same thing for the third model. The 3 models should be exported for each template defined in the project, so user can select any combianition for his truck. Be aware that's each layer is slightly translated from the others, so that the result should be different depending  on the order of the decals selected for each layer and if the decals are overlaying.

I'm going to make a test for Daf XF 105 to see if this solution is feasible.

**Comment by AdamLabrosse** [comment]
I think this feature could not be satisfactorily done.

Firstly, to add a second decal on the windcreen, we can use the addon spot on an accessory feature, like adding a light on front bumper. To add a third one, we would need to add a addon spot on the second decal and spots need to be separated by a gap to be able to differentiate the decals. This way second decals and third decals have different origin spots (both differerent from the first decal origin spot). But reference spot for addon in the configuration files is the accessory spot, so all addon spots are treated the same way and the third decal could be added on the second spot and then would be tranlated according to the windscreen. Not sure, it is understandable if you don't have investigated the feature.

Secondly, the windscreen model for exterior and interior view are strangely different. It(s not a problem for accessories because because SCS has added the possibility the define one model for the exterior view and one model for the interior view in the accessory configuration file. But for accessory addon, only one model could be defined. Then second decals model needs to have exterior model for the front of the windscreen and the interior model for the back of the windscreen. In the interior view, there is no problem because, we only see the back of the windcreen. But for the exterior view, we can see both the front and the back of the windscreen, and then some graphic bug could appear like colision between first and second decals, or second decal not placed at the good place on the windscreen or covering a part of the cabin, depending on the position of the decals on the windscreen.

For now, I think we need to keep only one decal on windscreen until accessory addon system is improved by SCS.
