### ISSUE TITLE
Introduce default autosave feature to Docs > MS2 > autosave

### ISSUE THREAD

**Issue by pete-agreatguy** [WerewolfCustoms/ModsStudio2IssueBoard#91]
**Is your feature request related to a problem? Please describe.**
Not related to a problem. More user friendly feature.

**Describe the solution you'd like**
Introduction of having a default autosave directory set to the following location:

Documents > Mods Studio 2 > autosave

See screenshot here.
![ms2_idea_as](https://user-images.githubusercontent.com/74508456/108077164-25506b80-7064-11eb-8392-3eafa749232b.png)

**Describe alternatives you've considered**
n/a

**Additional context**
Need to agree or come up with a default auto save time. Suggest every 5-10 mins?

**Comment by WerewolfCustoms** [comment]
I have to familiarize myself with the autosave feature again... I think we had something in the lines of this request...

**Comment by WerewolfCustoms** [comment]
**So, here's how Auto-Save function works:**

1.  AutoSave function is enabled/disabled by option #1
2. AutoSave path can be entered in the options. If left empty, the AutoSave function defaults to `MyDocuments\Mods Studio 2\AutoSave`
3. AutoSave interval can be entered in options. if left empty (0), the AutoSave function defaults to 5 minute interval.

🆕 **Updated in v2021.03** 🆕

I've changed the options so that (for new users), the defaults will be pre-entered.
AutoSave will still be turned OFF by default.
